# Generated by Django 3.1.3 on 2022-04-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='text',
            field=models.FileField(upload_to='specs'),
        ),
    ]
