# Generated by Django 3.1.3 on 2022-04-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_dart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dart',
            name='text',
            field=models.CharField(max_length=100000),
        ),
    ]
