# Generated by Django 3.1.3 on 2022-04-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220426_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dart',
            name='text',
            field=models.CharField(max_length=10000000000),
        ),
    ]
