# Generated by Django 3.1.3 on 2022-04-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220426_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dart',
            name='text',
            field=models.TextField(max_length=1000000),
        ),
    ]
