# Generated by Django 3.1.3 on 2022-04-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_getimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dart',
            name='text',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterModelTable(
            name='getimage',
            table=None,
        ),
    ]
