# Generated by Django 3.1.3 on 2022-04-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220427_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dart',
            name='text',
            field=models.TextField(max_length=1000000),
        ),
    ]
